export const uaLocationsList = [
  {
    city: 'Kyiv',
    lat: 50.45,
    lng: 30.5233,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyiv, Misto',
    capital: 'primary',
  },
  {
    city: 'Kharkiv',
    lat: 49.9925,
    lng: 36.2311,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kharkivska Oblast',
    capital: 'admin',
  },
  {
    city: 'Odesa',
    lat: 46.4775,
    lng: 30.7326,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Odeska Oblast',
    capital: 'admin',
  },
  {
    city: 'Dnipro',
    lat: 48.4675,
    lng: 35.04,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: 'admin',
  },
  {
    city: 'Donetsk',
    lat: 48.0028,
    lng: 37.8053,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'admin',
  },
  {
    city: 'Lviv',
    lat: 49.8425,
    lng: 24.0322,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: 'admin',
  },
  {
    city: 'Zaporizhzhia',
    lat: 47.85,
    lng: 35.1175,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zaporizka Oblast',
    capital: 'admin',
  },
  {
    city: 'Bazal’tove',
    lat: 50.6765,
    lng: 26.16,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Rivnenska Oblast',
    capital: '',
  },
  {
    city: 'Kryvyi Rih',
    lat: 47.91,
    lng: 33.39,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: 'minor',
  },
  {
    city: 'Sevastopol',
    lat: 44.605,
    lng: 33.5225,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Sevastopol, Misto',
    capital: 'admin',
  },
  {
    city: 'Mykolaiv',
    lat: 46.975,
    lng: 31.995,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Mykolaivska Oblast',
    capital: 'admin',
  },
  {
    city: 'Mariupol',
    lat: 47.0958,
    lng: 37.5494,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'minor',
  },
  {
    city: 'Luhansk',
    lat: 48.5678,
    lng: 39.3031,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: 'admin',
  },
  {
    city: 'Vinnytsia',
    lat: 49.2333,
    lng: 28.4833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Vinnytska Oblast',
    capital: 'admin',
  },
  {
    city: 'Makiivka',
    lat: 48.0556,
    lng: 37.9611,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'minor',
  },
  {
    city: 'Simferopol',
    lat: 44.9519,
    lng: 34.1022,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: 'admin',
  },
  {
    city: 'Chernihiv',
    lat: 51.4939,
    lng: 31.2947,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Chernihivska Oblast',
    capital: 'admin',
  },
  {
    city: 'Poltava',
    lat: 49.5894,
    lng: 34.5514,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Poltavska Oblast',
    capital: 'admin',
  },
  {
    city: 'Kherson',
    lat: 46.6425,
    lng: 32.625,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khersonska Oblast',
    capital: 'admin',
  },
  {
    city: 'Khmelnytskyi',
    lat: 49.4167,
    lng: 27.0,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khmelnytska Oblast',
    capital: 'admin',
  },
  {
    city: 'Cherkasy',
    lat: 49.4444,
    lng: 32.0597,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Cherkaska Oblast',
    capital: 'admin',
  },
  {
    city: 'Sumy',
    lat: 50.9119,
    lng: 34.8028,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Sumska Oblast',
    capital: 'admin',
  },
  {
    city: 'Chernivtsi',
    lat: 48.3,
    lng: 25.9333,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Chernivetska Oblast',
    capital: 'admin',
  },
  {
    city: 'Zhytomyr',
    lat: 50.25,
    lng: 28.6667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zhytomyrska Oblast',
    capital: 'admin',
  },
  {
    city: 'Horlivka',
    lat: 48.3,
    lng: 38.05,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'minor',
  },
  {
    city: 'Rivne',
    lat: 50.6192,
    lng: 26.2519,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Rivnenska Oblast',
    capital: 'admin',
  },
  {
    city: 'Ivano-Frankivsk',
    lat: 48.9228,
    lng: 24.7106,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ivano-Frankivska Oblast',
    capital: 'admin',
  },
  {
    city: 'Kropyvnytskyi',
    lat: 48.5,
    lng: 32.2667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kirovohradska Oblast',
    capital: 'admin',
  },
  {
    city: 'Kamianske',
    lat: 48.5167,
    lng: 34.6167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: 'minor',
  },
  {
    city: 'Ternopil',
    lat: 49.5667,
    lng: 25.6,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ternopilska Oblast',
    capital: 'admin',
  },
  {
    city: 'Kremenchuk',
    lat: 49.0631,
    lng: 33.4039,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Poltavska Oblast',
    capital: 'minor',
  },
  {
    city: 'Lutsk',
    lat: 50.75,
    lng: 25.3358,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Volynska Oblast',
    capital: 'admin',
  },
  {
    city: 'Bila Tserkva',
    lat: 49.7989,
    lng: 30.1153,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Sievierodonetsk',
    lat: 48.9481,
    lng: 38.4933,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: 'minor',
  },
  {
    city: 'Kerch',
    lat: 45.3619,
    lng: 36.4711,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: 'minor',
  },
  {
    city: 'Melitopol',
    lat: 46.8489,
    lng: 35.3675,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zaporizka Oblast',
    capital: 'minor',
  },
  {
    city: 'Kramatorsk',
    lat: 48.7392,
    lng: 37.5839,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'minor',
  },
  {
    city: 'Khrustalnyi',
    lat: 48.1214,
    lng: 38.9453,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Uzhhorod',
    lat: 48.6239,
    lng: 22.295,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zakarpatska Oblast',
    capital: 'admin',
  },
  {
    city: 'Sloviansk',
    lat: 48.8533,
    lng: 37.625,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Brovary',
    lat: 50.5111,
    lng: 30.79,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Yevpatoriia',
    lat: 45.1939,
    lng: 33.3681,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: 'minor',
  },
  {
    city: 'Berdiansk',
    lat: 46.7556,
    lng: 36.7889,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zaporizka Oblast',
    capital: 'minor',
  },
  {
    city: 'Alchevsk',
    lat: 48.4778,
    lng: 38.7978,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: 'minor',
  },
  {
    city: 'Nikopol',
    lat: 47.5667,
    lng: 34.4,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: 'minor',
  },
  {
    city: 'Pavlohrad',
    lat: 48.5167,
    lng: 35.8667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: 'minor',
  },
  {
    city: 'Kamianets-Podilskyi',
    lat: 48.6833,
    lng: 26.5833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khmelnytska Oblast',
    capital: 'minor',
  },
  {
    city: 'Lysychansk',
    lat: 48.9167,
    lng: 38.4,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Dovzhansk',
    lat: 48.0778,
    lng: 39.6472,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: 'minor',
  },
  {
    city: 'Mukacheve',
    lat: 48.45,
    lng: 22.75,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zakarpatska Oblast',
    capital: 'minor',
  },
  {
    city: 'Konotop',
    lat: 51.2167,
    lng: 33.2,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Sumska Oblast',
    capital: 'minor',
  },
  {
    city: 'Uman',
    lat: 48.75,
    lng: 30.2167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Cherkaska Oblast',
    capital: 'minor',
  },
  {
    city: 'Yenakiieve',
    lat: 48.2167,
    lng: 38.2,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Yalta',
    lat: 44.4994,
    lng: 34.17,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Shostka',
    lat: 51.8667,
    lng: 33.4833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Sumska Oblast',
    capital: 'minor',
  },
  {
    city: 'Stakhanov',
    lat: 48.5681,
    lng: 38.6586,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Drohobych',
    lat: 49.35,
    lng: 23.5,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Kostiantynivka',
    lat: 48.5333,
    lng: 37.7167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Bakhmut',
    lat: 48.5947,
    lng: 38.0008,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'minor',
  },
  {
    city: 'Fedosiia',
    lat: 45.0342,
    lng: 35.3792,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Kovel',
    lat: 51.2167,
    lng: 24.7167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Volynska Oblast',
    capital: 'minor',
  },
  {
    city: 'Nizhyn',
    lat: 51.0381,
    lng: 31.8861,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Chernihivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Smila',
    lat: 49.2117,
    lng: 31.8731,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Cherkaska Oblast',
    capital: 'minor',
  },
  {
    city: 'Chervonohrad',
    lat: 50.3867,
    lng: 24.2289,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Pokrovsk',
    lat: 48.2828,
    lng: 37.1828,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'minor',
  },
  {
    city: 'Pervomaisk',
    lat: 48.0439,
    lng: 30.85,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Mykolaivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Korosten',
    lat: 50.95,
    lng: 28.6333,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zhytomyrska Oblast',
    capital: 'minor',
  },
  {
    city: 'Kolomyia',
    lat: 48.5306,
    lng: 25.0403,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ivano-Frankivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Rubizhne',
    lat: 49.01,
    lng: 38.3714,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Khartsyzk',
    lat: 48.0428,
    lng: 38.1425,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Druzhkivka',
    lat: 48.6214,
    lng: 37.5278,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Chornomorsk',
    lat: 46.3017,
    lng: 30.6569,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Odeska Oblast',
    capital: '',
  },
  {
    city: 'Bilhorod-Dnistrovskyi',
    lat: 46.1833,
    lng: 30.35,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Odeska Oblast',
    capital: 'minor',
  },
  {
    city: 'Irpin',
    lat: 50.5167,
    lng: 30.25,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Chystiakove',
    lat: 48.0219,
    lng: 38.6264,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Stryi',
    lat: 49.25,
    lng: 23.85,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Novohrad-Volynskyi',
    lat: 50.5833,
    lng: 27.6333,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zhytomyrska Oblast',
    capital: 'minor',
  },
  {
    city: 'Lozova',
    lat: 48.8833,
    lng: 36.3833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kharkivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Antratsyt',
    lat: 48.1192,
    lng: 39.09,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Horishni Plavni',
    lat: 49.0167,
    lng: 33.6667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Poltavska Oblast',
    capital: '',
  },
  {
    city: 'Myrnohrad',
    lat: 48.2911,
    lng: 37.2681,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Shakhtarsk',
    lat: 48.0469,
    lng: 38.4686,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: 'minor',
  },
  {
    city: 'Okhtyrka',
    lat: 50.303,
    lng: 34.892,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Sumska Oblast',
    capital: 'minor',
  },
  {
    city: 'Snizhne',
    lat: 48.0283,
    lng: 38.7656,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Rovenky',
    lat: 48.0711,
    lng: 39.3428,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Fastiv',
    lat: 50.0833,
    lng: 29.9167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Lubny',
    lat: 50.0167,
    lng: 33.0,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Poltavska Oblast',
    capital: 'minor',
  },
  {
    city: 'Brianka',
    lat: 48.5133,
    lng: 38.6431,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Krasnodon',
    lat: 48.3,
    lng: 39.7333,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Romny',
    lat: 50.75,
    lng: 33.4667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Sumska Oblast',
    capital: 'minor',
  },
  {
    city: 'Myrhorod',
    lat: 49.9667,
    lng: 33.6,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Poltavska Oblast',
    capital: 'minor',
  },
  {
    city: 'Podilsk',
    lat: 47.7419,
    lng: 29.535,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Odeska Oblast',
    capital: 'minor',
  },
  {
    city: 'Vyshneve',
    lat: 50.3869,
    lng: 30.3581,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Vasylkiv',
    lat: 50.1783,
    lng: 30.3158,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Dubno',
    lat: 50.3931,
    lng: 25.735,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Rivnenska Oblast',
    capital: 'minor',
  },
  {
    city: 'Boryslav',
    lat: 49.2892,
    lng: 23.4189,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: '',
  },
  {
    city: 'Bucha',
    lat: 50.5486,
    lng: 30.2208,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Holubivske',
    lat: 48.6333,
    lng: 38.65,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Boyarka',
    lat: 50.3292,
    lng: 30.2886,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Yasynuvata',
    lat: 48.1278,
    lng: 37.8625,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Slavuta',
    lat: 50.3028,
    lng: 26.8683,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khmelnytska Oblast',
    capital: '',
  },
  {
    city: 'Sambir',
    lat: 49.5167,
    lng: 23.2028,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Toretsk',
    lat: 48.3917,
    lng: 37.8733,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Zhmerynka',
    lat: 49.05,
    lng: 28.1,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Vinnytska Oblast',
    capital: 'minor',
  },
  {
    city: 'Chuhuiv',
    lat: 49.8356,
    lng: 36.6864,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kharkivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Novoyavorovskoye',
    lat: 49.9311,
    lng: 23.5731,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: '',
  },
  {
    city: 'Mohyliv-Podilskyi',
    lat: 48.45,
    lng: 27.7833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Vinnytska Oblast',
    capital: 'minor',
  },
  {
    city: 'Truskavets',
    lat: 49.2806,
    lng: 23.505,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: '',
  },
  {
    city: 'Dobropillia',
    lat: 48.4689,
    lng: 37.0828,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Kupiansk',
    lat: 49.7167,
    lng: 37.5833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kharkivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Pereyaslav-Khmel’nyts’kyy',
    lat: 50.065,
    lng: 31.445,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Khmilnyk',
    lat: 49.5569,
    lng: 27.9572,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Vinnytska Oblast',
    capital: 'minor',
  },
  {
    city: 'Kirovsk',
    lat: 48.6375,
    lng: 38.6428,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Sofiyivs’ka Borshchahivka',
    lat: 50.4114,
    lng: 30.3692,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Perevalsk',
    lat: 48.4333,
    lng: 38.8167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: 'minor',
  },
  {
    city: 'Vynohradiv',
    lat: 48.1497,
    lng: 23.025,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zakarpatska Oblast',
    capital: 'minor',
  },
  {
    city: 'Armiansk',
    lat: 46.1074,
    lng: 33.6919,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Saky',
    lat: 45.1336,
    lng: 33.5772,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: 'minor',
  },
  {
    city: 'Debaltseve',
    lat: 48.3333,
    lng: 38.4,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Selydove',
    lat: 48.15,
    lng: 37.3039,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Molodohvardiisk',
    lat: 48.3444,
    lng: 39.6583,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Merefa',
    lat: 49.8167,
    lng: 36.05,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kharkivska Oblast',
    capital: '',
  },
  {
    city: 'Bilohorodka',
    lat: 50.3942,
    lng: 30.2314,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Sukhodilsk',
    lat: 48.35,
    lng: 39.7167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Pelahiivka',
    lat: 48.0989,
    lng: 38.6128,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Hostomel',
    lat: 50.5692,
    lng: 30.2653,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Taromske',
    lat: 48.4617,
    lng: 34.7828,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: '',
  },
  {
    city: 'Vynnyky',
    lat: 49.8156,
    lng: 24.1297,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: '',
  },
  {
    city: 'Chervonopartyzansk',
    lat: 48.0833,
    lng: 39.7833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Mykolaivka',
    lat: 48.8521,
    lng: 37.774,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Nyzhnia Krynka',
    lat: 48.1144,
    lng: 38.1606,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Antonivka',
    lat: 46.6808,
    lng: 32.7358,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khersonska Oblast',
    capital: '',
  },
  {
    city: 'Petrovske',
    lat: 48.2833,
    lng: 38.8833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Prymorskyi',
    lat: 45.1167,
    lng: 35.4806,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Chasiv Yar',
    lat: 48.5884,
    lng: 37.8359,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Zhdanivka',
    lat: 48.1375,
    lng: 38.2608,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Vakhrusheve',
    lat: 48.1667,
    lng: 38.8333,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Hirnyk',
    lat: 48.05,
    lng: 37.3667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Lymanka',
    lat: 46.3883,
    lng: 30.6808,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Odeska Oblast',
    capital: '',
  },
  {
    city: 'Soledar',
    lat: 48.6953,
    lng: 38.0675,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Sartana',
    lat: 47.1667,
    lng: 37.6833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Haspra',
    lat: 44.4361,
    lng: 34.1106,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Inkerman',
    lat: 44.6,
    lng: 33.6,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Sevastopol, Misto',
    capital: '',
  },
  {
    city: 'Korolevo',
    lat: 48.15,
    lng: 23.1333,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zakarpatska Oblast',
    capital: '',
  },
  {
    city: 'Sniatyn',
    lat: 48.45,
    lng: 25.5667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ivano-Frankivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Novgorodskoye',
    lat: 48.3319,
    lng: 37.8364,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Sieverne',
    lat: 48.0858,
    lng: 38.6942,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Sofiivka',
    lat: 48.2603,
    lng: 38.1594,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Teplohirsk',
    lat: 48.5967,
    lng: 38.5828,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Bilenke',
    lat: 48.7664,
    lng: 37.6314,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Hurzuf',
    lat: 44.5528,
    lng: 34.2875,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Horodenka',
    lat: 48.6675,
    lng: 25.5003,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ivano-Frankivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Pivnichne',
    lat: 48.3886,
    lng: 37.9067,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Yasenivskyi',
    lat: 48.1606,
    lng: 39.2175,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Liubymivka',
    lat: 48.0397,
    lng: 39.44,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Masandra',
    lat: 44.5167,
    lng: 34.1833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Bilky',
    lat: 48.3294,
    lng: 23.1397,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zakarpatska Oblast',
    capital: '',
  },
  {
    city: 'Yasnohirka',
    lat: 48.7675,
    lng: 37.5669,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Bilytske',
    lat: 48.4086,
    lng: 37.1796,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Pochaiv',
    lat: 50.0028,
    lng: 25.5097,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ternopilska Oblast',
    capital: '',
  },
  {
    city: 'Oleksandrivka',
    lat: 46.3294,
    lng: 30.6336,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Odeska Oblast',
    capital: '',
  },
  {
    city: 'Vuhlehirsk',
    lat: 48.31,
    lng: 38.27,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Zorynsk',
    lat: 48.4167,
    lng: 38.6167,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Komyshany',
    lat: 46.6364,
    lng: 32.1703,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khersonska Oblast',
    capital: '',
  },
  {
    city: 'Oleksiievo-Druzhkivka',
    lat: 48.5806,
    lng: 37.6147,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Piskivka',
    lat: 50.7078,
    lng: 29.595,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Holmivskyi',
    lat: 48.4006,
    lng: 38.0797,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Novodruzhesk',
    lat: 48.9634,
    lng: 38.352,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Karnaukhivka',
    lat: 48.4714,
    lng: 34.7369,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: '',
  },
  {
    city: 'Velikaya Berëzovitsa',
    lat: 49.4964,
    lng: 25.6086,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ternopilska Oblast',
    capital: '',
  },
  {
    city: 'Rozkishne',
    lat: 48.4922,
    lng: 39.2719,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Vorzel',
    lat: 50.55,
    lng: 30.15,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Shepetivka',
    lat: 50.1833,
    lng: 27.0667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khmelnytska Oblast',
    capital: 'minor',
  },
  {
    city: 'Halych',
    lat: 49.1247,
    lng: 24.7286,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ivano-Frankivska Oblast',
    capital: 'minor',
  },
  {
    city: 'Petropavlivs’ka Borshchahivka',
    lat: 50.4338,
    lng: 30.3286,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Balabyne',
    lat: 47.7442,
    lng: 35.2203,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zaporizka Oblast',
    capital: '',
  },
  {
    city: 'Staryi Krym',
    lat: 47.1597,
    lng: 37.4869,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Zelenivka',
    lat: 46.7178,
    lng: 32.6544,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Khersonska Oblast',
    capital: '',
  },
  {
    city: 'Chornukhyne',
    lat: 48.3264,
    lng: 38.5156,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Kotsyubyns’ke',
    lat: 50.49,
    lng: 30.3347,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyiv, Misto',
    capital: '',
  },
  {
    city: 'Koreiz',
    lat: 44.4331,
    lng: 34.0872,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Bryukhovychi',
    lat: 49.9039,
    lng: 23.9539,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: '',
  },
  {
    city: 'Horenka',
    lat: 50.5569,
    lng: 30.3175,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Chabany',
    lat: 50.3403,
    lng: 30.4228,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Teple',
    lat: 48.3328,
    lng: 39.5422,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Zalizne',
    lat: 48.375,
    lng: 37.8733,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Khotiv',
    lat: 50.3333,
    lng: 30.4667,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Novooleksandrivka',
    lat: 48.3454,
    lng: 34.9969,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: '',
  },
  {
    city: 'Zaozerne',
    lat: 45.1606,
    lng: 33.285,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Almazna',
    lat: 48.5167,
    lng: 38.5833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Shabelkivka',
    lat: 48.7608,
    lng: 37.4881,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Obroshino',
    lat: 49.7853,
    lng: 23.8686,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Lvivska Oblast',
    capital: '',
  },
  {
    city: 'Krykhivtsi',
    lat: 48.9008,
    lng: 24.6662,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ivano-Frankivska Oblast',
    capital: '',
  },
  {
    city: 'Novopillia',
    lat: 47.9539,
    lng: 33.5278,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Dnipropetrovska Oblast',
    capital: '',
  },
  {
    city: 'Zaitseve',
    lat: 48.4292,
    lng: 38.0094,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Simeiz',
    lat: 44.4058,
    lng: 33.99,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Novosilky',
    lat: 50.3544,
    lng: 30.4544,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyiv, Misto',
    capital: '',
  },
  {
    city: 'Yasynivka',
    lat: 48.1358,
    lng: 37.9303,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Kryukivshchyna',
    lat: 50.3683,
    lng: 30.3681,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Shakhtarske',
    lat: 48.0497,
    lng: 39.5528,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Mykhaylivka-Rubezhivka',
    lat: 50.5003,
    lng: 30.1458,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Valianivske',
    lat: 48.0767,
    lng: 39.5611,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Malokaterynivka',
    lat: 47.6581,
    lng: 35.26,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zaporizka Oblast',
    capital: '',
  },
  {
    city: 'Yuzhna Lomuvatka',
    lat: 48.4375,
    lng: 38.5311,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Shcherbynivka',
    lat: 48.3886,
    lng: 37.9067,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Vylok',
    lat: 48.1147,
    lng: 22.8319,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Zakarpatska Oblast',
    capital: '',
  },
  {
    city: 'Tovste',
    lat: 48.8464,
    lng: 25.7253,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Ternopilska Oblast',
    capital: '',
  },
  {
    city: 'Piatypillia',
    lat: 48.0119,
    lng: 38.0919,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Hatne',
    lat: 50.3583,
    lng: 30.3989,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kyivska Oblast',
    capital: '',
  },
  {
    city: 'Bulavynske',
    lat: 48.255,
    lng: 38.3336,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Dubove',
    lat: 48.1261,
    lng: 39.6433,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Kulynychi',
    lat: 49.9819,
    lng: 36.3861,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Kharkivska Oblast',
    capital: '',
  },
  {
    city: 'Sadky',
    lat: 49.009,
    lng: 33.4602,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Poltavska Oblast',
    capital: '',
  },
  {
    city: 'Krasnotorka',
    lat: 48.6858,
    lng: 37.5267,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Pervomaiskyi',
    lat: 47.9736,
    lng: 38.7875,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Brytivka',
    lat: 46.1722,
    lng: 30.2833,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Odeska Oblast',
    capital: '',
  },
  {
    city: 'Blyzhnie',
    lat: 45.0569,
    lng: 35.3306,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Krym, Avtonomna Respublika',
    capital: '',
  },
  {
    city: 'Mykhailivka',
    lat: 48.0683,
    lng: 39.2633,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Laryne',
    lat: 47.8828,
    lng: 37.9294,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Donetska Oblast',
    capital: '',
  },
  {
    city: 'Vedmezhe',
    lat: 48.1242,
    lng: 39.5856,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Luhanska Oblast',
    capital: '',
  },
  {
    city: 'Volodymyr-Volynskyi',
    lat: 50.8525,
    lng: 24.3236,
    country: 'Ukraine',
    iso2: 'UA',
    region: 'Volynska Oblast',
    capital: 'minor',
  },
];
